---
- name: Setup LAMP
  hosts: webservers
  become: yes

  tasks:
  - name: Install Apache
    apt: 
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    
  - name: Install Httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
