---
- name: Create and Manage Users in Linux
  hosts: webservers
  become: yes

  tasks:
  - name: Create user
    user:
      name: "{{ item }}"
      shell: /bin/bash
    loop:                     # It will place the value in the place of item one by one and create users.
      - hunter
      - ishu
      - ishwar